src/utils/u60_representation.nr
Works around https://github.com/noir-lang/noir/issues/5823
=> fix: workaround shifts to compile with latest noir

.github/NIGHTLY_CANARY_DIED.md, .github/workflows/nightly-canary.yml, .github/workflows/test.yml
Resolves 
This PR adds a new workflow which runs the tests on nightly releases of nargo and raises an issue if they start failing.
=> chore: add a canary for tests failing on nightly releases of nargo

src/runtime_bignum.nr, src/utils/arrayX.nr
Resolves 
I've removed the generic from `ArrayX.__normalize_limbs()` and created a separate impl so that this method is only implemented for `ArrayX<Field, _, _>`
=> fix: remove unnecessary generic from `ArrayX.__normalize_limbs()`

src/runtime_bignum.nr
Fixes an issue with the `from_be_bytes` preventing the use of the function when the number of bits of the bytes passed as argument is the same as the number of bits encoding the modulus.
```rust
fn from_be_bytes<let NBytes: u32>(x: [u8; NBytes]) -> BigNum<N, Params> {
let num_bits = NBytes * 8;
let modulus_bits = Params::modulus_bits();
assert(num_bits > modulus_bits);
assert(num_bits - modulus_bits < 8);
...
}
```
In the original code, when `num_bits` yields the same value as `modulus_bits` the assert fails and the function is usuable.
As this behavior is not desired, simply replacing the strictly greater than with a greater than or equal fixes the issue:
```rust
fn from_be_bytes<let NBytes: u32>(x: [u8; NBytes]) -> BigNum<N, Params> {
let num_bits = NBytes * 8;
let modulus_bits = …
```
=> fix: issue with bit check in `from_be_bytes`

.github/workflows/nightly-canary.yml, src/utils/u60_representation.nr
Resolves #29 
This PR removes the formatter from the nightly canary as changes to formatting doesn't indicate a breaking change/regression as the tests do.
=> chore: remove formatter from canary

README.md, migration_notes.md
Added a warning banner to the readme, with a link to some migration notes, to help external devs adjust to the new structs.
=> chore: migration notes

src/fns/unconstrained_helpers.nr, src/fns/unconstrained_ops.nr
Resolves #41 
This generic is unnecessary and just causes errors when it can't be bound.
=> fix: remove unnecessary generic

src/runtime_bignum.nr, src/utils/split_bits.nr
Resolves 
This PR reworks the `split_120_bits` and `split_60_bits functions to abuse the truncation we perform when casting to avoid the need to perform byte decompositions (and the massive blowup in execution trace that brings)
=> feat: optimize brillig execution of `split_X_bits` functions

src/fns/unconstrained_helpers.nr
Resolves 
This PR removes a bunch of unnecessary mutation from the unconstrained code to avoid needing to handle stores/loads and for mem2reg to need to try and remove them again.
=> feat: remove a bunch of unnecessary bytecode from unconstrained ops

src/bignum.nr, src/fields/secp256r1Fq.nr, src/lib.nr, src/tests/bignum_test.nr
Although not explained in the original code, there's a reason why arrays of size `N` are never passed to/from setters and getters of `BigNum`; it's so that external libs can write use a generic `BigNum` `where BigNum: BigNumTrait`, without having to specify an `N`. Removal of `from_array` and `get_limbs` resolves this.
Also resolves a modulus_bits typo in one of the off-the-shelf params files.
=> feat: remove generic parameter from the `BigNum` trait

src/bignum.nr
Changes in https://github.com/noir-lang/noir-bignum/pull/44 inadvertently increased gate counts. This seems to fix it.
=> fix: constraint count regression introduced in commit 53f652b 

migration_notes.md
Thanks leopardracer for https://github.com/noir-lang/noir-bignum/pull/57. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.
=> chore: redo typo PR by leopardracer

README.md
`dep` prefix was deprecated long time ago
=> chore: remove dep prefix from readme

.github/workflows/test.yml, Nargo.toml, README.md, src/bignum.nr, src/fns/constrained_ops.nr, src/fns/unconstrained_ops.nr, src/runtime_bignum.nr, src/tests/bignum_test.nr
While working on having Noir require traits to be in scope I noticed this new error pops up in a usage of this library:
We could import the corresponding trait, but I realized the traits here maybe meant to have `Add`, `Neg`, etc., as parent traits except that until recently it was impossible.
As a bonus, now we can use `+`, `-`, etc. with big nums.
=> feat!: remove redefinition of arithmetic methods on `BigNumTrait`

README.md
Listing a noir version as a dependency is redundant with describing which versions the library is tested against. References to barretenberg are not useful here and just add more info which will fall out of sync, e.g. https://github.com/noir-lang/noir-bignum/pull/84
=> chore: remove references to barretenberg in documentation

src/bignum.nr
Resolves 
This is implied by the trait constraint so we don't need to declare it again on the trait.
=> chore: remove unnecessary default implementation of `Eq`

src/fns/constrained_ops.nr
Resolves #91 
Constrain ops via `evaluate_quadratic_expression` only in constrained context.
@TomAFrench should`validate_gt::<_, MOD_BITS>(divisor, remainder);` from `fn udiv_mod` also be inside `if !std::runtime::is_unconstrained()`?
=> feat: constrain ops only in constrained context

src/bignum.nr
Resolves #64 
More clear what it does and aligns with stdlib `U128::zero()`.
=> feat: add zero constructor

src/bignum.nr, src/fns/constrained_ops.nr, src/runtime_bignum.nr, src/tests/bignum_test.nr, src/tests/runtime_bignum_test.nr
adds an `is_zero` constrained fn
closes #56
=> feat: Add `is_zero`

src/bignum.nr
Resolves 
This PR implements the `Default` trait on `BigNum`
=> feat: implement `Default` trait on `BigNum`

.github/workflows/benchmark.yml, src/bignum.nr, src/fns/unconstrained_ops.nr, src/params.nr, src/runtime_bignum.nr, src/tests/bignum_test.nr
Resolves 
This got broken in #79
=> fix: correct batch inversion function

src/fns/unconstrained_helpers.nr, src/fns/unconstrained_ops.nr, src/tests/bignum_test.nr, src/utils/split_bits.nr
=> fix: fixed the array length bug when normalizing limbs in multiplication 

src/bignum.nr, src/tests/bignum_test.nr
…constants
Resolves 
This works around https://github.com/noir-lang/noir/issues/8096 by injecting a constant equal to the associated constant rather than trying to read it off of the trait.
=> fix: replace references to associated constants with macro-generated constants

src/bignum.nr, src/fns/constrained_ops.nr, src/fns/unconstrained_helpers.nr, src/fns/unconstrained_ops.nr, src/runtime_bignum.nr
=> chore: avoid passing `params` object around unnecessarily

src/benchmarks/bignum_benchmarks.nr
=> chore: add benchmarks for more field types (BLS377Fq, BLS377Fr, BLS381Fr) 

src/bignum.nr, src/fns/unconstrained_ops.nr
Towards https://github.com/noir-lang/noir/pull/7843
=> fix: remove unused generics

src/runtime_bignum.nr
Towards https://github.com/noir-lang/noir/pull/8686
I'm not sure how this compiled before https://github.com/noir-lang/noir/pull/8686: the `as_array` call converted the slice to an array, then I think with implicit rules it was converted back to a slice. But... what's the size of that intermediate array? It can't be deduced. Removing the `as_array` call fixes this, as I think it was never needed (and I think the comment on top of the function saying we can't return slice might be outdated).
=> fix: remove `as_array` call for which `N` cannot be deduced

src/fns/unconstrained_helpers.nr
For https://github.com/noir-lang/noir/pull/8703
=> fix: do not cast numeric to bool

src/fns/unconstrained_helpers.nr, src/utils/msb.nr
Resolves https://github.com/noir-lang/noir-bignum/issues/136
Working on implementing and testing the __get_msb function to work similarly to __get_msb64 but using get_msb128 directly.
Found a working 128-bit de bruijn sequence with no collision by brute force.
=> fix: Refactor __get_msb to work on a single 128bit debrujin sequence

src/bignum.nr, src/fns/constrained_ops.nr, src/runtime_bignum.nr
Simplifies the conditional_select function by replacing the arithmetic-based selection logic with a simple if-statement. As shown in https://github.com/noir-lang/noir-bignum/pull/184, this change improves circuit size benchmarks.
Resolves
=> feat: remove conditional select from Bignum

.github/workflows/benchmark.yml, .github/workflows/test.yml, src/fns/unconstrained_helpers.nr
Modify bit-shifts for the new bit-shift semantic from https://github.com/noir-lang/noir/pull/9373
=> fix: switch to new bit shifts semantic
